version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: tpi-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tpi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tpi-network

networks:
  tpi-network:
    driver: bridge

