version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tpi-postgres
    restart: always
    environment:
      POSTGRES_DB: tpi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  admin-service:
    build: ./tpi-admin-service
    container_name: tpi-admin-service
    depends_on:
      - postgres
    ports:
      - "8081:8081"

  vehiculos-service:
    build: ./tpi-vehiculos-service
    container_name: tpi-vehiculos-service
    depends_on:
      - postgres
    ports:
      - "8082:8082"

  reportes-service:
    build: ./tpi-reportes-service
    container_name: tpi-reportes-service
    depends_on:
      - postgres
    ports:
      - "8083:8083"

  gateway:
    build: ./tpi-gateway-service
    container_name: tpi-gateway
    depends_on:
      - admin-service
      - vehiculos-service
      - reportes-service
    ports:
      - "8080:8080"
