
CREATE TABLE Marcas (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL
);

CREATE TABLE Modelos (
    ID SERIAL PRIMARY KEY,
    DESCRIPCION VARCHAR(255),
    ID_MARCA INTEGER NOT NULL,
    CONSTRAINT Modelos_Marcas_FK FOREIGN KEY (ID_MARCA) REFERENCES Marcas(ID)
);

CREATE TABLE Vehiculos (
    ID SERIAL PRIMARY KEY,
    PATENTE VARCHAR(255) NOT NULL,
    ID_MODELO INTEGER NOT NULL,
    ANIO INTEGER NOT NULL,
    CONSTRAINT Vehiculos_Modelos_FK FOREIGN KEY (ID_MODELO) REFERENCES Modelos(ID)
);

CREATE TABLE Empleados (
    LEGAJO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    TELEFONO_CONTACTO VARCHAR(255) NOT NULL
);

CREATE TABLE Interesados (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO_DOCUMENTO VARCHAR(3) NOT NULL,
    DOCUMENTO VARCHAR(10) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    RESTRINGIDO INTEGER DEFAULT 0,
    NRO_LICENCIA INTEGER,
    FECHA_VENCIMIENTO_LICENCIA DATE
);

CREATE TABLE Pruebas (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FECHA_HORA_INICIO TIMESTAMP NOT NULL,
    FECHA_HORA_FIN TIMESTAMP,
    COMENTARIOS TEXT,
    ID_EMPLEADO BIGINT,
    ID_INTERESADO BIGINT,
    ID_VEHICULO BIGINT,
    CONSTRAINT Pruebas_Empleados_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES Empleados(LEGAJO),
    CONSTRAINT Pruebas_Interesados_FK FOREIGN KEY (ID_INTERESADO) REFERENCES Interesados(ID),
    CONSTRAINT Pruebas_Vehiculos_FK FOREIGN KEY (ID_VEHICULO) REFERENCES Vehiculos(ID)
);

CREATE TABLE Posiciones (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_VEHICULO INTEGER NOT NULL,
    FECHA_HORA TIMESTAMP NOT NULL,
    LATITUD DOUBLE PRECISION NOT NULL,
    LONGITUD DOUBLE PRECISION NOT NULL,
    CONSTRAINT Posiciones_Vehiculos_FK FOREIGN KEY (ID_VEHICULO) REFERENCES Vehiculos(ID)
);

CREATE TABLE Notificaciones (
    ID SERIAL PRIMARY KEY,
    MENSAJE TEXT NOT NULL,
    TIPO VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(255) NOT NULL,
    FECHA TIMESTAMP NOT NULL,
    ID_PRUEBA BIGINT NOT NULL,
    TIPO_INCIDENTE VARCHAR(255),
    CONSTRAINT Notificaciones_Pruebas_FK FOREIGN KEY (ID_PRUEBA) REFERENCES Pruebas(ID)
);

CREATE TABLE Zonas_Peligrosas (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    LAT_NOROESTE DOUBLE PRECISION NOT NULL,
    LON_NOROESTE DOUBLE PRECISION NOT NULL,
    LAT_SURESTE DOUBLE PRECISION NOT NULL,
    LON_SURESTE DOUBLE PRECISION NOT NULL
);

CREATE TABLE Tipos_Incidente (
    ID SERIAL PRIMARY KEY,
    NOMBRE_INCIDENTE VARCHAR(255) NOT NULL
);
ALTER INDEX tipos_incidente_pkey RENAME TO Tipos_Incidente_PK;

CREATE TABLE Incidentes (
    ID_PRUEBA BIGINT GENERATED ALWAYS AS IDENTITY  PRIMARY KEY ,
    NRO_INCIDENTE INTEGER GENERATED ALWAYS AS IDENTITY  PRIMARY KEY ,
    ID_TIPO_INCIDENTE INTEGER NOT NULL,
    FECHA_HORA TIMESTAMP NOT NULL,
    CONSTRAINT Incidentes_Pruebas_FK FOREIGN KEY (ID_PRUEBA) REFERENCES Pruebas(ID)
    CONSTRAINT Incidentes_PK PRIMARY KEY (ID_PRUEBA, NRO_INCIDENTE),
    CONSTRAINT  Incidentes_TipoIncidente_FK FOREIGN KEY (ID_TIPO_INCIDENTE) REFERENCES Tipos_Incidente (ID),
)




ALTER INDEX zonas_peligrosas_pkey RENAME TO Zonas_Peligrosas_PK;

-- Renombrar las PK generadas por defecto
ALTER INDEX vehiculos_pkey RENAME TO Vehiculos_PK;
ALTER INDEX empleados_pkey RENAME TO Empleados_PK;
ALTER INDEX interesados_pkey RENAME TO Interesados_PK;
ALTER INDEX pruebas_pkey RENAME TO Pruebas_PK;
ALTER INDEX posiciones_pkey RENAME TO Posiciones_PK;
ALTER INDEX notificaciones_pkey RENAME TO Notificaciones_PK;
ALTER INDEX marcas_pkey RENAME TO Marcas_PK;
ALTER INDEX modelos_pkey RENAME TO Modelos_PK;
